project:
  type: website

website:
  title: "RiverFlow"
  navbar:
    left:
      - 2023_MP.qmd
      - 2023_DV.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/HollyRiver?tab=repositories
      - icon: book
        href: https://blog.naver.com/hc_ssk2800
format:
  html:
    theme: minty
    css: styles.css
    backgroundcolor: whitesmoke