project:
  type: website

website:
  title: "RiverFlow"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/HollyRiver?tab=repositories
      - icon: book
        href: https://blog.naver.com/hc_ssk2800
format:
  html:
    theme: minty
    css: styles.css
    monobackgroundcolor: #aacf93
    backgroundcolor: #aacf93
    


